version: "3.8"

services:
  app:
    build: .
    container_name: douyin-live-recorder-webui

    ports:
      - "5000:5000"

    environment:
      - TERM=xterm-256color
      - TZ=Asia/Shanghai

    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./backup_config:/app/backup_config
      - ./downloads:/app/downloads

    restart: unless-stopped

    tty: true
    stdin_open: true